### PR TITLE
Log when a parameter is set

### LINKED ISSUE #86: Option to print parameter values
I have been using this library and I am really happy with it - thanks for the contribution!

This issue is more of a question/feature request: can we log the parameters that are loaded by the parameter listener? This would be very useful for debugging purposes.

### PR DESCRIPTION
**Pull request by tylerjw**
Fixes #86

If you build this locally, you can test this by running the example node with debug logging:
```shell
ros2 run generate_parameter_library_example test_node --ros-args --params-file src/generate_parameter_library/example/config/implementation.yaml --log-level debug
```

Then in another terminal change a parameter:
```shell
ros2 param set /admittance_controller control.frame.id new_frame
```

You should see an output like this in the logs:
```
[DEBUG] [1681944620.098785049] [admittance_controller]: control.frame.id: string = new_frame
```

### CODE REVIEW

**Review by abake48 — APPROVED** [review]
tested and lgtm

**Comment by tylerjw** [comment]
Thank you

**Review by christophfroehlich — COMMENTED** [review]
It works, LGTM (except for the missing dash in your instructions ;) `--params-file`).

I'm just wondering: At the first run, all parameters are listed in the debug output. After changing .frame.id, there is an output line with the change of this parameter but also a subset of other parameters (pid. and gains. structure. I guess all __map - parameters?). Is this intentional?

**Comment by christophfroehlich** [comment]
ok, I just saw that at the beginning "all" parameters are written, at run-time only the changed one and the __map parameters.

**Review by christophfroehlich — APPROVED** [review]

**Comment by tylerjw** [comment]
> ok, I just saw that at the beginning "all" parameters are written, at run-time only the changed one and the __map parameters.

The reason the map parameters are re-read after any parameter change is it accounts for if you change the key parameter for the map. Re-reading in the library also will declare any parameters that have not been declared and give them default values in the map. Eventually, I hope to fix this by detecting when the key is changed and only re-reading the map parameters then.

**Pull request merged**
